language: node_js
node_js:
  - "8.11.4"
script:
  - echo "Deploying!"
install:
  - npm install
  - react-scripts build
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN